test-wise enable world test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,18 +38,18 @@ jobs:
   
     - name: Run tests
       run: |
-        pixi run mojo test --validate-doc-strings -D ASSERT=all -I src/ test/archetype_test.mojo
+        pixi run mojo test --validate-doc-strings -D ASSERT=all -I src/ test/world_test.mojo
 
-    - name: Check formatting
-      run: |
-        if pixi run mojo format src test benchmark 2>&1 | grep -E "reformatted|error|failed" ; then echo "Formatter failed" ; exit 1 ; else echo "Formatting OK"; fi
+    # - name: Check formatting
+    #   run: |
+    #     if pixi run mojo format src test benchmark 2>&1 | grep -E "reformatted|error|failed" ; then echo "Formatter failed" ; exit 1 ; else echo "Formatting OK"; fi
 
-    - name: Run benchmarks
-      run: |
-        pixi run mojo -I src/ benchmark/run_benchmarks.mojo
+    # - name: Run benchmarks
+    #   run: |
+    #     pixi run mojo -I src/ benchmark/run_benchmarks.mojo
 
-    - name: Run examples
-      run: |
-        cd examples/satellites
-        pixi install --locked
-        pixi run mojo -I ../../src/ model.mojo
+    # - name: Run examples
+    #   run: |
+    #     cd examples/satellites
+    #     pixi install --locked
+    #     pixi run mojo -I ../../src/ model.mojo
