Reverse order

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,13 +29,13 @@ jobs:
       run: |
         source /home/runner/.bash_profile 
         magic install --locked
-
-    - name: Check formatting
-      run: |
-        source /home/runner/.bash_profile 
-        if mojo format *.mojo 2>&1 | grep -E "reformatted|error|failed" ; then echo "Formatter failed" ; exit 1 ; else echo "Formatting OK"; fi
   
     - name: Run tests
       run: |
         source /home/runner/.bash_profile 
         magic run mojo test --validate-doc-strings --sanitize address src/
+
+    - name: Check formatting
+      run: |
+        source /home/runner/.bash_profile 
+        if mojo format *.mojo 2>&1 | grep -E "reformatted|error|failed" ; then echo "Formatter failed" ; exit 1 ; else echo "Formatting OK"; fi
