ci: update test execution

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,16 +1,15 @@
 name: Build and test
 
-on: 
+on:
   push:
     branches:
-    - main
+      - main
   pull_request:
 
 permissions: {}
 
 jobs:
   build_and_test:
-
     runs-on: ubuntu-latest
 
     defaults:
@@ -18,31 +17,31 @@ jobs:
         shell: bash -ieo pipefail {0}
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-    - name: Install pixi CLI
-      run: |
-        curl -fsSL https://pixi.sh/install.sh | sh
-        
-    - name: Install mojo and dependencies
-      run: |
-        pixi install --locked
-  
-    - name: Run tests
-      run: |
-        pixi run mojo test --validate-doc-strings -D ASSERT=all -I src/ test
+      - name: Install pixi CLI
+        run: |
+          curl -fsSL https://pixi.sh/install.sh | sh
 
-    - name: Check formatting
-      run: |
-        if pixi run mojo format src test benchmark 2>&1 | grep -E "reformatted|error|failed" ; then echo "Formatter failed" ; exit 1 ; else echo "Formatting OK"; fi
+      - name: Install mojo and dependencies
+        run: |
+          pixi install --locked
 
-    - name: Run benchmarks
-      run: |
-        pixi run mojo -I src/ benchmark/run_benchmarks.mojo
+      - name: Run tests
+        run: |
+          pixi run mojo run --Werror -D ASSERT=all -I src test/_all.mojo
 
-    - name: Run examples
-      run: |
-        cd examples/satellites
-        pixi install --locked
-        pixi run mojo -I ../../src/ model.mojo
+      - name: Check formatting
+        run: |
+          if pixi run mojo format src test benchmark 2>&1 | grep -E "reformatted|error|failed" ; then echo "Formatter failed" ; exit 1 ; else echo "Formatting OK"; fi
+
+      - name: Run benchmarks
+        run: |
+          pixi run mojo -I src/ benchmark/run_benchmarks.mojo
+
+      - name: Run examples
+        run: |
+          cd examples/satellites
+          pixi install --locked
+          pixi run mojo -I ../../src/ model.mojo
